name: Release

on:
  push:
    tags:
      - "v1.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build binaries
        run: npm run build:all

      - name: version
        run: echo "::set-output name=version::$(./dist/linux-x64/cloud-archive version)"
        id: version

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          title: ${{ steps.version.outputs.version }}
          tag: ${{ github.ref }}
          files: |
            dist/win-arm64/cloud-archive.exe
            dist/win-x64/cloud-archive.exe
            dist/linux-arm64/cloud-archive
            dist/linux-x64/cloud-archive
            dist/macos-arm64/cloud-archive
            dist/macos-x64/cloud-archive
