name: Release

on:
  push:
    tags:
      - "v1.*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build binaries
        run: npm run build:all

      - name: version
        run: echo "RELEASE_VERSION=$(./dist/linux-x64/cloud-archive version)" >> $GITHUB_OUTPUT
        id: version

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          title: ${{ env.RELEASE_VERSION }}
          tag: ${{ github.ref }}
          files: |
            dist/tar/win-arm64
            dist/tar/win-x64.tar
            dist/tar/linux-arm64.tar
            dist/tar/linux-x64.tar
            dist/tar/macos-arm64.tar
            dist/tar/macos-x64.tar
