name: Release

on:
  push:
    tags:
      - "v1.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build binaries
        run: npm run build:all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/macos-x64/cloud-archive
            dist/macos-arm64/cloud-archive
            dist/linux-x64/cloud-archive
            dist/linux-arm64/cloud-archive
            dist/win-x64/cloud-archive.exe
            dist/win-arm64/cloud-archive.exe
